# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@4.1.1 # The Windows orb give you everything you need to start using the Windows executor.

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    executor:
      name: win/default # executor type
      size: medium # can be medium, large, xlarge, 
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - add_ssh_keys:
          fingerprints:
            - "73:e8:c5:f5:7c:59:ca:75:18:8e:ef:9e:a3:af:1f:85"
      - checkout
      - run:
          name: "Install"
          command: "npm install"
      - run:
          name: "Build"
          command: "npm build"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
